# Generated by Django 2.0 on 2020-12-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='adscripcion',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
