# Generated by Django 2.0 on 2020-12-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(unique=True),
        ),
    ]
