# Generated by Django 2.0 on 2020-12-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionWithMultipleOption',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('voting.question',),
        ),
        migrations.CreateModel(
            name='QuestionWithUniqueOption',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('voting.question',),
        ),
    ]
