# Generated by Django 2.0 on 2020-12-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
