# Generated by Django 2.0 on 2020-12-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_questionwithmultipleoption_questionwithuniqueoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleOptionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('option', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_options', to='voting.Question')),
            ],
        ),
    ]
