# Generated by Django 2.0 on 2020-12-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='usuario',
            new_name='started_by',
        ),
    ]
