# Generated by Django 2.0 on 2020-12-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_multipleoptionquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleoptionquestion',
            name='option',
        ),
    ]
