# Generated by Django 2.0 on 2020-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_multipleoptionquestion_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options_type',
            field=models.PositiveIntegerField(choices=[('1', 'Unique option'), ('2', 'Multiple option')], default='1'),
        ),
    ]
