# Generated by Django 2.0 on 2020-12-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_question_options_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleoptionquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionWithMultipleOption',
        ),
        migrations.DeleteModel(
            name='QuestionWithUniqueOption',
        ),
        migrations.AlterField(
            model_name='question',
            name='options_type',
            field=models.PositiveIntegerField(choices=[(1, 'Unique option'), (2, 'Multiple option')], default='1'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='MultipleOptionQuestion',
        ),
    ]
