# Generated by Django 2.0 on 2020-12-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20201219_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='options_type',
            new_name='options',
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='voting.Question'),
        ),
    ]
