# Generated by Django 2.0 on 2020-12-21 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20201221_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='options',
            new_name='option_types',
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.Question'),
        ),
    ]
