# Generated by Django 2.0 on 2020-12-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20201221_1657'),
        ('voting', '0005_auto_20201221_1844'),
    ]

    operations = [
    ]
