# Generated by Django 2.0 on 2020-12-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_merge_20201223_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='rank_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_types',
            field=models.PositiveIntegerField(choices=[(1, 'Unique option'), (2, 'Multiple option'), (3, 'Rank order scale')], default='1'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
