# Generated by Django 2.0 on 2020-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20201223_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
