# Generated by Django 2.0 on 2020-12-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20201223_1928'),
        ('voting', '0012_merge_20201224_1300'),
    ]

    operations = [
    ]
