# Generated by Django 2.0 on 2020-12-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20201221_1040'),
        ('voting', '0013_auto_20201223_1928'),
    ]

    operations = [
    ]
