# Generated by Django 2.0 on 2020-12-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_merge_20201226_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='question',
            field=models.ManyToManyField(related_name='voting', to='voting.Question'),
        ),
    ]
