# Generated by Django 2.0 on 2021-01-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_auto_20201226_1223'),
        ('voting', '0014_merge_20201224_1307'),
    ]

    operations = [
    ]
