# Generated by Django 2.0 on 2021-01-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20201228_1943'),
        ('voting', '0014_question_points'),
        ('voting', '0014_merge_20201224_1307'),
    ]

    operations = [
    ]
