# Generated by Django 2.0 on 2021-01-01 13:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_merge_20210101_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='tallyF',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='tallyM',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
