# Generated by Django 2.0 on 2021-01-01 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_auto_20210101_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.TypeVoting'),
            preserve_default=False,
        ),
    ]
