# Generated by Django 2.0 on 2021-01-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0021_auto_20210101_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'IDENTITY'), (1, 'BORDA'), (2, 'HONDT'), (3, 'EQUALITY'), (4, 'SAINTE_LAGUE'), (5, 'DROOP'), (6, 'IMPERIALI'), (7, 'HARE')], default='0'),
        ),
    ]
