# Generated by Django 2.0 on 2021-01-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0022_auto_20210102_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='rank_order',
        ),
    ]
