# Generated by Selenium IDE
from django.test import TestCase
from django.contrib.staticfiles.testing import StaticLiveServerTestCase

import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from base.tests import BaseTestCase
from authentication.models import UserProfile

class TestVotingDuplicateNameViewNegative(StaticLiveServerTestCase):
  def setUp(self):
    self.base = BaseTestCase()
    self.base.setUp()
    user_admin_superuser = UserProfile(username='adminsuper', sex='F', style='N', is_staff=True, is_superuser=True)
    user_admin_superuser.set_password('qwerty')
    user_admin_superuser.save()
    self.base.user_admin = user_admin_superuser

    self.driver = webdriver.Firefox()
    self.vars = {}
    self.driver.maximize_window() #For maximizing window
    self.driver.implicitly_wait(20) #gives an implicit wait for 20 seconds

    super().setUp() 
  
  def tearDown(self):
    super().tearDown()
    self.driver.quit()

    self.base.tearDown()

  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_duplicate_voting_name_view_negative(self):
    # Test name: Votación con mismo nombre
    # Step # | name | target | value
    # 1 | open | http://localhost:8000/admin/ | 
    self.driver.get(f'{self.live_server_url}/admin/')
    self.driver.find_element_by_id("id_username").send_keys("adminsuper")
    self.driver.find_element_by_id("id_password").send_keys("qwerty")
    self.driver.find_element_by_css_selector("div .submit-row input").click()
    # 3 | click | css=.model-voting .addlink | 
    self.driver.find_element(By.CSS_SELECTOR, ".model-voting .addlink").click()
    # 4 | type | id=id_name | name1
    self.driver.find_element(By.ID, "id_name").send_keys("name1")
    # 5 | type | id=id_desc | name1
    self.driver.find_element(By.ID, "id_desc").send_keys("name1")
    # 6 | click | css=#add_id_question > img | 
    self.vars["window_handles"] = self.driver.window_handles
    # 7 | storeWindowHandle | root | 
    self.driver.find_element(By.CSS_SELECTOR, "#add_id_question > img").click()
    # 8 | selectWindow | handle=${win989} | 
    self.vars["win989"] = self.wait_for_window(2000)
    # 9 | click | id=id_desc | 
    self.vars["root"] = self.driver.current_window_handle
    # 10 | type | id=id_options-0-number | 1
    self.driver.switch_to.window(self.vars["win989"])
    # 11 | click | id=id_options-0-number | 
    self.driver.find_element(By.ID, "id_desc").click()
    # 12 | type | id=id_desc | name1
    self.driver.find_element(By.ID, "id_options-0-number").send_keys("1")
    # 13 | click | id=id_options-0-option | 
    self.driver.find_element(By.ID, "id_options-0-number").click()
    # 14 | type | id=id_options-1-number | 1
    self.driver.find_element(By.ID, "id_desc").send_keys("name1")
    # 15 | click | id=id_options-1-number | 
    self.driver.find_element(By.ID, "id_options-0-option").click()
    # 16 | type | id=id_options-1-number | 2
    self.driver.find_element(By.ID, "id_options-1-number").send_keys("2")
    # 19 | type | id=id_options-0-option | 1
    self.driver.find_element(By.ID, "id_options-1-number").click()
    # 20 | click | id=id_options-1-option | 
    element = self.driver.find_element(By.ID, "id_options-1-number")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 21 | type | id=id_options-1-option | 2
    self.driver.find_element(By.ID, "id_options-0-option").send_keys("1")
    # 22 | click | name=_save | 
    self.driver.find_element(By.ID, "id_options-1-option").click()
    # 23 | close |  | 
    self.driver.find_element(By.ID, "id_options-1-option").send_keys("2")
    # 24 | selectWindow | handle=${root} | 
    self.driver.find_element(By.NAME, "_save").click()
    # 25 | selectWindow | handle=${win5557} | 
    # 26 | type | id=id_name | name1
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, "#add_id_auths > img").click()
    # 28 | click | id=id_url | 
    self.vars["win5557"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    # 29 | click | id=id_url | 
    self.driver.switch_to.window(self.vars["win5557"])
    # 30 | type | id=id_url | http://localhost:8000
    self.driver.find_element(By.ID, "id_name").send_keys("name1")
    # 31 | click | name=_save | 
    self.driver.find_element(By.ID, "id_url").click()
    # 32 | close |  | 
    self.driver.find_element(By.ID, "id_url").click()
    # 33 | selectWindow | handle=${root} | 
    self.driver.find_element(By.ID, "id_url").click()
    # 34 | click | name=_save | 
    self.driver.find_element(By.ID, "id_url").send_keys("http://localhost:8000/")
    # 35 | click | css=.addlink | 
    self.driver.find_element(By.NAME, "_save").click()
    # 36 | type | id=id_name | name1
    # 37 | click | name=_save | 
    self.driver.switch_to.window(self.vars["root"])
    # 38 | assertText | css=.field-name li | Voting with this Name already exists.
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
    self.driver.find_element(By.ID, "id_name").send_keys("name1")
    self.driver.find_element(By.NAME, "_save").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".field-name li").text == "Voting with this Name already exists."
  
