# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSuccess():
  def setup_method(self, method):
    self.base = BaseTestCase()
    self.base.setUp()
    
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_success(self):
    self.driver.get("http://localhost:8000/")
    self.driver.find_element(By.ID, "signIn").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > #username").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > #username").send_keys("prueba10")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("prueba10@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, "#\\__BVID__18 .custom-control:nth-child(1) > .custom-control-label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\__BVID__21 .custom-control:nth-child(1) > .custom-control-label").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > #password").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > #password").send_keys("prueba10")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > #password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "btn-abrir-popup").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("prueba10")
    self.driver.find_element(By.CSS_SELECTOR, "#\\__BVID__12 > div").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("prueba10")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.ID, "welcomeID").text == "Welcome"
    assert self.driver.find_element(By.CSS_SELECTOR, "strong:nth-child(2)").text == "prueba10!"
  


    