# Generated by Django 2.0 on 2021-01-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210112_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex (M/F)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='style',
            field=models.CharField(choices=[('N', 'Normal'), ('T', 'Tritanopia'), ('O', 'Night'), ('C', 'Color blind')], default='N', help_text='Designates which style will be shown to the user across pages; helpful for people with difficulties distinguishing colors.', max_length=1, verbose_name='Style (N/T/O/C)'),
        ),
    ]
