# Generated by Django 2.0 on 2020-12-28 23:21

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='c',
            field=base.models.BigBigField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='d',
            field=base.models.BigBigField(default=0),
            preserve_default=False,
        ),
    ]
