# Generated by Django 2.0 on 2020-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_vote_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='question_id',
            field=models.PositiveIntegerField(),
        ),
    ]
