# Generated by Django 2.0 on 2021-01-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201226_1449'),
        ('store', '0004_auto_20201228_2321'),
    ]

    operations = [
    ]
