# Generated by Django 2.0 on 2021-01-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_vote_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='c',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='d',
        ),
        migrations.AlterField(
            model_name='vote',
            name='a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='b',
            field=models.TextField(),
        ),
    ]
